server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web: # http://127.0.0.1:18082/actuator/nacosconfig
      exposure:
        include: '*'
spring:
  application:
    name: xxiaohei-gateway
  cloud:
    gateway:
      routes:
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer1/**
          filters:
            - StripPrefix=1
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      config:
        namespace: ${spring.profiles.active}
        contextPath: /nacos
        prefix: ${spring.application.name}
        file-extension: yaml
      discovery:
        namespace: ${spring.profiles.active}
        ephemeral: true #true为临时实例、false为持久化实例
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?refresh=true